name: Taiko Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '14.x'
    - name: Install dependencies
      run: |
          npm install
          
    - name: Install Gauge
      run: |
        npm install -g @getgauge/cli

    - name: Install Taiko
      run: |
        npm install taiko

    - name: Prep gauge-js
      run: |
        git clone https://github.com/getgauge/gauge-js.git
        cd gauge-js
        npm install
      shell: bash

    - name: Install gauge-js
      run: |
        cd gauge-js
        npm run installPlugin


    - name: install browser dependencies
      run: |
        cd gauge-taiko-test
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libxcomposite1 \
          libcups2 \
          libxrandr2 \
          libpangocairo-1.0-0 \
          libgtk-3-0 \
          libgbm-dev 
